first_app/config/routes.rb
Rails.application.routes.draw do
  

  resource :sessions, only: [ :new, :create, :destroy ]

  resources :users
  get '/sandbox' => 'root#sandbox' if Rails.env.development?
  root to:'root#home' # this maps / to the root#home action

end

first_app/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	before_save { self.email = email.downcase }
	before_save { self.session_token ||= Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64.to_s) }
	validates :name, presence: true, length: { maximum: 30 }
	validates :email, format: { with: /\A[^@]+@[^@]+\z/ }, uniqueness: true
end

first_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :authenticate_user
end

first_app/app/controllers/root_controller.rb
class RootController < ApplicationController
  def home
  end

  def sandbox
  	#session[:our_data] = 1234
  end
end

first_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user, only: [ :new, :create ]

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
				sign_in(@user)
        flash[:success] = "Welcome back, #{@user.name}!"
        redirect_to @user
    else
        flash.now[:error] = "Invalid email/password combination"
        render "new"
    end  	
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end
end

first_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: [ :new, :create ]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { 
			sign_in(@user)
        	flash[:success] = "Wellcome, #{@user.name}!"
        	redirect_to root_path
        }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

first_app/app/helpers/root_helper.rb
module RootHelper
end

first_app/app/helpers/sessions_helper.rb
module SessionsHelper
  def authenticate_user
    unless signed_in?
      flash[:notice] = "Please sign-in to continue"
      redirect_to new_sessions_path
    end
  end

  def sign_in(user)
      session[:session_token] = user.session_token
  end

  def signed_in?
      !current_user.nil?
  end

  def current_user
      @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def current_user?(user)
    current_user == user
  end

  def sign_out
  	@current_user = nil
  	session.delete(:session_token)
  end
end

first_app/app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

first_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codecamp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- New header -->
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
          <%= link_to "CodeCamp", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= current_user.name %> <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Sign out", sessions_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Register", new_user_path %></li>
                <li><%= link_to "Sign in", new_sessions_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
    </div>
</header>

<!-- Content wrapped in container -->
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>  
  <%= yield %>
  <!-- New footer -->
  <footer class="footer">
    <small>
      <a href="http://codecamp.io">程式開發工作營</a>
    </small>
    <br>
  </footer>
  <!-- Debugging footer -->
  <%= content_tag :div, debug(params) if Rails.env.development? %>
</div>

</body>
</html>

first_app/app/views/root/home.html.erb
<h1>Wellcome to FirstApp</h1>
<center>
	<%= link_to "Sign-in", "#", class:"btn btn-large btn-primary" %> <br>
	<%= link_to "Register!", "#" %>
</center>

first_app/app/views/root/sandbox.html.erb
<h1>Wellcome to FirstApp</h1>
<center>
	<%= "our_data = #{session[:our_data]}" %>
</center>